package net.srcdemo.ui;

public interface Strings
{
	final String btnActivate = "Activate";
	final String btnBrowse = "Browse...";
	final String btnDeactivate = "Deactivate";
	final String btnQuit = "Quit";
	final String cmdHostFramerate = "host_framerate ";
	final String errDirectoriesEqual = "Directories must not be equal";
	final String errDokanNotInstalled = "Dokan is not installed.\n\nMore information will be available if you start in debug mode.";
	final String errDokanTitle = "Dokan error";
	final String errInvalidBacking = "Invalid folder to save frames.";
	final String errInvalidDokan = "The version of Dokan installed is not the correct one.\nThis application required Dokan 0.6.";
	final String errInvalidMountpoint = "Invalid folder where the game will save frames.";
	final String errMountpointNotEmpty = "Folder where the game will save frames is not empty.";
	final String lblAudioType = "Audio output:";
	final String lblBlendRate = "Motion blur blend rate: ";
	final String lblEffectiveFps = "Effective recording FPS: ";
	final String lblInvalidSettings = "Invalid settings: ";
	final String lblJpegQuality = "JPEG quality";
	final String lblLastFrameProcessed = "Last frame processed: ";
	final String lblLastFrameProcessedDefault = "N/A";
	final String lblLastFrameSaved = "Last frame saved: ";
	final String lblLastFrameSavedDefault = "N/A";
	final String lblMakeSureFramerate = "Make sure to set host_framerate before you start rendering!";
	final String lblPressWhenReady = "Press \"Activate\" when ready.";
	final String lblReadyToRender = "Ready to render.";
	final String lblShutterAngle = "Simulated shutter angle: ";
	final String lblTargetFps = "Final video FPS: ";
	final String lblTgaCompressionRLE = "TGA RLE compression";
	final String lblVideoDisabled = "When video is disabled, the video framerate doesn't matter.\nHowever, it is recommended to record at\nmore than 60 frames to avoid a bug in Source Recorder\ncausing some sounds to not be played at all when playing\na demo at a low framerate compared to the game's tickrate.";
	final String lblVideoType = "Video output:";
	final String spnBlendRatePlural = " frames per frame";
	final String spnBlendRateSingular = " frame (identity)";
	final String spnShutterAnglePlural = " degrees";
	final String spnShutterAngleSingular = " degree";
	final String spnTargetFpsPlural = " frames per second";
	final String spnTargetFpsSingular = " frame per second";
	final String step1 = "1. Select the folder where the game will save frames.";
	final String step1Dialog = "Select the folder where you want the final frames to be saved.";
	final String step2 = "2. Select the folder where you want the final frames to be saved.\n(Must be a different directory!)";
	final String step2Dialog = "Select the folder where the game will save frames.";
	final String step3 = "3. Set parameters";
	final String tabAudio = "Audio";
	final String tabVideo = "Video";
	final String videoOptDisabled = "Disabled (Audio only)";
	final String videoOptJpg = "JPG";
	final String videoOptPng = "PNG";
	final String videoOptTga = "TGA";
	final String windowTitle = "SrcDemo²";
}
